CREATE DATABASE ecommercedb;

CREATE TABLE product (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(25) NOT NULL,
  subcategory VARCHAR(25) NOT NULL,
  price NUMERIC NOT NULL,
  sizes VARCHAR(10)[] NOT NULL,
  images TEXT[] NOT NULL
);

CREATE TABLE user (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(25) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100),
  google_id VARCHAR(255) UNIQUE,
  role VARCHAR(50) DEFAULT 'user'
);

CREATE TABLE cart_item (
  cart_id INTEGER NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES product(id),
  quantity INTEGER NOT NULL,
  size VARCHAR(10) NOT NULL,
  PRIMARY KEY (cart_id, product_id, size)
);

CREATE TABLE cart (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);

UPDATE "user"
SET role = 'admin'
WHERE email = 'admin1@gmail.com';

CREATE TABLE address (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  address_line1 VARCHAR(100),
  address_line2 VARCHAR(100),
  city VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL,
  zip_code VARCHAR(25) NOT NULL,
  phone VARCHAR(25) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);
